/// Files: kernel/trace/trace.c
/// Fix: 4397f04575c44e1440ec2e49b6302785c95fd2f8
/// Fixes: 737223fbca3b1c91feb947c7f571b35749b743b6
/// Version: 1.0.8

virtual detect

@err_buffer exists@
identifier buf;
position p;
@@

allocate_trace_buffer(..., struct trace_buffer *buf, ...)
{
	...
	buf->data = alloc_percpu(struct trace_array_cpu);
	if (!buf->data) {
*		ring_buffer_free@p(buf->buffer);
		... when != buf->buffer = NULL;
	}
	...
}

@err_buffers exists@
identifier tr;
position p;
@@

allocate_trace_buffers(struct trace_array *tr, ...)
{
	...
	tr->trace_buffer.data = alloc_percpu(struct trace_array_cpu);
*	if (!tr->trace_buffer.data@p) {
		... when != tr->trace_buffer = NULL;
	}
	...
}

@script:python depends on detect@
p << err_buffer.p;
@@

coccilib.report.print_report(p[0], 'ERROR: CVE-2017-18595')

@script:python depends on detect@
p << err_buffers.p;
@@

coccilib.report.print_report(p[0], 'ERROR: CVE-2017-18595')
