/// Files: drivers/net/can/usb/usb_8dev.c
/// Fix: 3d3925ff6433f98992685a9679613a2cc97f3ce2
/// Fixes: 0024d8ad1639e32d717445c69ca813fd19c2a91c

virtual detect

@usb_submit_urb_failed@
identifier err, urb, netdev, failed, skb;
statement S;
@@

usb_8dev_start_xmit(struct sk_buff *skb, struct net_device *netdev)
{
	...
*	can_put_echo_skb(skb, netdev, ...);
	...
*	err = usb_submit_urb(urb, ...);
	if (unlikely(err))
*		goto failed;
	else S
	...
}

@err depends on usb_submit_urb_failed@
identifier usb_submit_urb_failed.urb, usb_submit_urb_failed.netdev, usb_submit_urb_failed.failed, usb_submit_urb_failed.skb;
position p;
@@

usb_8dev_start_xmit(struct sk_buff *skb, struct net_device *netdev)
{
	...
failed:
	...
*	can_free_echo_skb(netdev, ...);
	...
*	dev_kfree_skb@p(skb);
	...
}

@script:python depends on detect@
p << err.p;
@@

coccilib.report.print_report(p[0], 'ERROR: CVE-2022-28388')
