/// Files: drivers/net/can/usb/mcba_usb.c
/// Fix: 04c9b00ba83594a29813d6b1fb8fdc93a3915174
/// Fixes: 51f3baad7de943780ce0c17bd7975df567dd6e14

virtual detect

@mcba_usb_xmit_failed@
identifier skb, netdev, err, xmit_failed;
@@

mcba_usb_start_xmit(struct sk_buff *skb, struct net_device *netdev)
{
	...
*	can_put_echo_skb(skb, ...);
	...
*	err = mcba_usb_xmit(...);
*	if (err)
*		goto xmit_failed;
	...
}

@err@
identifier mcba_usb_xmit_failed.skb, mcba_usb_xmit_failed.netdev, mcba_usb_xmit_failed.xmit_failed;
position p;
@@

mcba_usb_start_xmit(struct sk_buff *skb, struct net_device *netdev)
{
	...
xmit_failed:
	...
*	dev_kfree_skb@p(skb);
	...
}

@script:python depends on detect@
p << err.p;
@@

coccilib.report.print_report(p[0], 'ERROR: CVE-2022-28389')
